name: "Build"

on:
  push:
    branches:
    - "develop"
    - "master"
  pull_request:
    branches:
    - "develop"
    - "master"

jobs:
  build:

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
        - "7.3"
        - "7.4"
        - "8.0"

    steps:
    - uses: "actions/checkout@v2"

    - uses: "shivammathur/setup-php@v2"
      with:
        coverage: "none"
        php-version: "${{ matrix.php-version }}"

    - name: "Validate composer.json"
      run: "composer validate --strict"

    - name: "Cache dependencies"
      uses: "actions/cache@v2"
      with:
        path: "~/.composer/cache"
        key: "php-${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.json') }}"
        restore-keys: "php-${{ matrix.php-version }}-composer-"

    - name: "Install dependencies"
      run: "composer install --prefer-dist --no-interaction --no-progress"

    - name: "Run PHPUnit"
      run: "vendor/bin/phpunit"
